# Generated by Django 6.1.1 on 2026-09-08 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='familiar',
        ),
        migrations.AddField(
            model_name='alumno',
            name='familiares',
            field=models.ManyToManyField(blank=True, related_name='hijos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('dni', models.CharField(blank=True, max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('turno', models.CharField(blank=True, help_text='Ej: Mañana, Tarde', max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaAutorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=15)),
                ('foto_dni', models.ImageField(blank=True, null=True, upload_to='dnis_autorizados/')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizados', to='registros.alumno')),
            ],
        ),
    ]
