# Generated by Django 6.1.1 on 2026-09-23 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_remove_alumno_familiar_alumno_familiares_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='familiares',
        ),
        migrations.AlterField(
            model_name='aula',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_asignadas', to='registros.perfilprofesor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='familiares',
            field=models.ManyToManyField(blank=True, related_name='hijos', to='registros.perfilfamiliar'),
        ),
    ]
